#pragma once
#include <iostream>
#include <numeric>	
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <charconv>
#include <vector>
#include <deque>
#include <queue>
#include <execution>
#include <fstream>
#include <sstream>
#include <numeric>
#include <optional>
#include <limits>
#include <iterator>
#include <iomanip>
#include <string>
#include <utility>
#include <unordered_set>
#include <unordered_map>
#include <set>
#include <map>
#include <functional>

#include <Eigen/Eigen>